version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:jpdatabase.clm1e92bmggq.us-west-2.rds.amazonaws.com
  postgres_db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Job
      POSTGRES_PASSWORD: postgres